CREATE DATABASE PQR;

CREATE TABLE PQR.pqr(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	tipo_pqr VARCHAR(50) NOT NULL,
	correo VARCHAR(50) NOT NULL,
	documento VARCHAR(5pqr0) NOT NULL,
	nombre_completo VARCHAR(1000) NOT NULL,
	fecha DATE NOT NULL,
	repuesta LONGTEXT NULL,
	id_pqr INT NULL,
	peticion LONGTEXT NOT NULL
);